INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-blue-dragon-wyrmling', 'Appendix B: Creatures', 'Blue Dragon Wyrmling', '["Creature Descriptions"]', 100000, 'creature', 'Blue Dragon Wyrmling — Medium Dragon (Chromatic), Lawful Evil.
AC 17, HP 65 (10d8 + 20), Speed walk 30 ft., burrow 15 ft., fly 60 ft..
Abilities: STR 17 (+3), DEX 10 (+0), CON 15 (+2), INT 12 (+1), WIS 11 (+0), CHA 15 (+2).
Skills: Perception +4, Stealth +2.
Immunities: Lightning.
Senses: Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14.
Languages: Draconic.
Challenge: 3 (XP 700, PB +2).
Multiattack: The dragon makes two Rend attacks.
Rend: Melee Attack Roll +5, reach 5 ft. Hit: 8 (1d10 + 3) Slashing damage plus 3 (1d6) Lightning damage.
Lightning Breath (Recharge 5-6): Dexterity Saving Throw: DC 12, each creature in a 30-foot-long, 5-foot-wide Line. Failure: 21 (6d6) Lightning damage. Success: Half damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-blue-dragon-wyrmling', '{"name":"Blue Dragon Wyrmling","source":"MM''25 p48","size":"Medium","type":"Dragon (Chromatic)","alignment":"Lawful Evil","ac":17,"init":2,"hp_avg":65,"hp_formula":"10d8 + 20","speed":{"walk":30,"burrow":15,"fly":60},"cr":"3","xp":700,"pb":2,"abilities":{"str":{"score":17,"mod":3,"save":3},"dex":{"score":10,"mod":0,"save":2},"con":{"score":15,"mod":2,"save":2},"int":{"score":12,"mod":1,"save":1},"wis":{"score":11,"mod":0,"save":2},"cha":{"score":15,"mod":2,"save":2}},"skills":{"Perception":4,"Stealth":2},"immunities":["Lightning"],"senses":"Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14","languages":"Draconic","traits":[],"actions":[{"name":"Multiattack","text":"The dragon makes two Rend attacks."},{"name":"Rend","text":"Melee Attack Roll +5, reach 5 ft. Hit: 8 (1d10 + 3) Slashing damage plus 3 (1d6) Lightning damage."},{"name":"Lightning Breath (Recharge 5-6)","text":"Dexterity Saving Throw: DC 12, each creature in a 30-foot-long, 5-foot-wide Line. Failure: 21 (6d6) Lightning damage. Success: Half damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-bronze-dragon-wyrmling', 'Appendix B: Creatures', 'Bronze Dragon Wyrmling', '["Creature Descriptions"]', 100001, 'creature', 'Bronze Dragon Wyrmling — Medium Dragon (Metallic), Lawful Good.
AC 15, HP 39 (6d8 + 12), Speed walk 30 ft., fly 60 ft., swim 30 ft..
Abilities: STR 17 (+3), DEX 10 (+0), CON 15 (+2), INT 12 (+1), WIS 11 (+0), CHA 15 (+2).
Skills: Perception +4, Stealth +2.
Immunities: Lightning.
Senses: Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14.
Languages: Draconic.
Challenge: 2 (XP 450, PB +2).
Amphibious: The dragon can breathe air and water.
Multiattack: The dragon makes two Rend attacks.
Rend: Melee Attack Roll +5, reach 5 ft. Hit: 8 (1d10 + 3) Slashing damage.
Lightning Breath (Recharge 5-6): Dexterity Saving Throw: DC 12, each creature in a 40-foot-long, 5-foot-wide Line. Failure: 16 (3d10) Lightning damage. Success: Half damage.
Repulsion Breath: Strength Saving Throw: DC 12, each creature in a 30-foot Cone. Failure: The target is pushed up to 30 feet straight away from the dragon and has the Prone condition.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-bronze-dragon-wyrmling', '{"name":"Bronze Dragon Wyrmling","source":"MM''25 p58","size":"Medium","type":"Dragon (Metallic)","alignment":"Lawful Good","ac":15,"init":2,"hp_avg":39,"hp_formula":"6d8 + 12","speed":{"walk":30,"fly":60,"swim":30},"cr":"2","xp":450,"pb":2,"abilities":{"str":{"score":17,"mod":3,"save":3},"dex":{"score":10,"mod":0,"save":2},"con":{"score":15,"mod":2,"save":2},"int":{"score":12,"mod":1,"save":1},"wis":{"score":11,"mod":0,"save":2},"cha":{"score":15,"mod":2,"save":2}},"skills":{"Perception":4,"Stealth":2},"immunities":["Lightning"],"senses":"Blindsight 10 ft., Darkvision 60 ft., Passive Perception 14","languages":"Draconic","traits":[{"name":"Amphibious","text":"The dragon can breathe air and water."}],"actions":[{"name":"Multiattack","text":"The dragon makes two Rend attacks."},{"name":"Rend","text":"Melee Attack Roll +5, reach 5 ft. Hit: 8 (1d10 + 3) Slashing damage."},{"name":"Lightning Breath (Recharge 5-6)","text":"Dexterity Saving Throw: DC 12, each creature in a 40-foot-long, 5-foot-wide Line. Failure: 16 (3d10) Lightning damage. Success: Half damage."},{"name":"Repulsion Breath","text":"Strength Saving Throw: DC 12, each creature in a 30-foot Cone. Failure: The target is pushed up to 30 feet straight away from the dragon and has the Prone condition."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-salamander-fire-snake', 'Appendix B: Creatures', 'Salamander Fire Snake', '["Creature Descriptions"]', 100002, 'creature', 'Salamander Fire Snake — Medium Elemental, Neutral Evil.
AC 14, HP 27 (6d8), Speed walk 30 ft., climb 30 ft..
Abilities: STR 12 (+1), DEX 14 (+2), CON 11 (+0), INT 7 (-2), WIS 10 (+0), CHA 8 (-1).
Vulnerabilities: Cold.
Immunities: Fire.
Senses: Darkvision 60 ft., Passive Perception 10.
Languages: Understands Primordial but can''t speak.
Challenge: 1 (XP 200, PB +2).
Fire Aura: At the end of each of the salamander''s turns, each creature of the salamander''s choice in a 5-foot Emanation originating from the salamander takes 3 (1d6) Fire damage.
Bite: Melee Attack Roll +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage plus 3 (1d6) Fire damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-salamander-fire-snake', '{"name":"Salamander Fire Snake","source":"MM''25 p266","size":"Medium","type":"Elemental","alignment":"Neutral Evil","ac":14,"init":2,"hp_avg":27,"hp_formula":"6d8","speed":{"walk":30,"climb":30},"cr":"1","xp":200,"pb":2,"abilities":{"str":{"score":12,"mod":1,"save":1},"dex":{"score":14,"mod":2,"save":2},"con":{"score":11,"mod":0,"save":0},"int":{"score":7,"mod":-2,"save":-2},"wis":{"score":10,"mod":0,"save":0},"cha":{"score":8,"mod":-1,"save":-1}},"skills":{},"vulnerabilities":["Cold"],"immunities":["Fire"],"senses":"Darkvision 60 ft., Passive Perception 10","languages":"Understands Primordial but can''t speak","traits":[{"name":"Fire Aura","text":"At the end of each of the salamander''s turns, each creature of the salamander''s choice in a 5-foot Emanation originating from the salamander takes 3 (1d6) Fire damage."}],"actions":[{"name":"Bite","text":"Melee Attack Roll +4, reach 5 ft. Hit: 6 (1d8 + 2) Piercing damage plus 3 (1d6) Fire damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-fume-drake', 'Appendix B: Creatures', 'Fume Drake', '["Creature Descriptions"]', 100003, 'creature', 'Fume Drake — Small Elemental, typically Neutral.
AC 12, HP 22 (5d6 + 5), Speed walk 30 ft., fly 30 ft..
Abilities: STR 6 (-2), DEX 14 (+2), CON 12 (+1), INT 6 (-2), WIS 10 (+0), CHA 11 (+0).
Immunities: Fire, Poison, Poisoned.
Senses: Darkvision 60 ft., Passive Perception 10.
Languages: Draconic, Ignan.
Challenge: 1/4 (XP 50, PB +2).
Death Burst: When the fume drake dies, it explodes in a cloud of noxious fumes. Each creature within 5 feet of the fume drake must succeed on a DC 11 Constitution saving throw or take 4 (1d8) poison damage.
Unusual Nature: The fume drake doesn''t require food, drink, or sleep.
Bite: Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) fire damage.
Scalding Breath (Recharge 6): The fume drake exhales a 15-foot cone of scalding steam. Each creature in that area must make a DC 11 Dexterity saving throw, taking 4 (1d8) fire damage on a failed save, or half as much damage on a successful one.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-fume-drake', '{"name":"Fume Drake","source":"DoSI p41","size":"Small","type":"Elemental","alignment":"typically Neutral","ac":12,"init":2,"hp_avg":22,"hp_formula":"5d6 + 5","speed":{"walk":30,"fly":30},"cr":"1/4","xp":50,"pb":2,"abilities":{"str":{"score":6,"mod":-2,"save":-2},"dex":{"score":14,"mod":2,"save":2},"con":{"score":12,"mod":1,"save":1},"int":{"score":6,"mod":-2,"save":-2},"wis":{"score":10,"mod":0,"save":0},"cha":{"score":11,"mod":0,"save":0}},"skills":{},"immunities":["Fire","Poison","Poisoned"],"senses":"Darkvision 60 ft., Passive Perception 10","languages":"Draconic, Ignan","traits":[{"name":"Death Burst","text":"When the fume drake dies, it explodes in a cloud of noxious fumes. Each creature within 5 feet of the fume drake must succeed on a DC 11 Constitution saving throw or take 4 (1d8) poison damage."},{"name":"Unusual Nature","text":"The fume drake doesn''t require food, drink, or sleep."}],"actions":[{"name":"Bite","text":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) fire damage."},{"name":"Scalding Breath (Recharge 6)","text":"The fume drake exhales a 15-foot cone of scalding steam. Each creature in that area must make a DC 11 Dexterity saving throw, taking 4 (1d8) fire damage on a failed save, or half as much damage on a successful one."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-ghoul', 'Appendix B: Creatures', 'Ghoul', '["Creature Descriptions"]', 100004, 'creature', 'Ghoul — Medium Undead, Chaotic Evil.
AC 12, HP 22 (5d8), Speed walk 30 ft..
Abilities: STR 13 (+1), DEX 15 (+2), CON 10 (+0), INT 7 (-2), WIS 10 (+0), CHA 6 (-2).
Immunities: Poison, Charmed, Exhaustion, Poisoned.
Senses: Darkvision 60 ft., Passive Perception 10.
Languages: Common.
Challenge: 1 (XP 200, PB +2).
Multiattack: The ghoul makes two Bite attacks.
Bite: Melee Attack Roll +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage plus 3 (1d6) Necrotic damage.
Claw: Melee Attack Roll +4, reach 5 ft. Hit: 4 (1d4 + 2) Slashing damage. If the target isn''t Undead or elf, it is subjected to: Constitution Saving Throw DC 10. Failure: The target has the Paralyzed condition until the end of its next turn.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-ghoul', '{"name":"Ghoul","source":"MM''25 p132","size":"Medium","type":"Undead","alignment":"Chaotic Evil","ac":12,"init":2,"hp_avg":22,"hp_formula":"5d8","speed":{"walk":30},"cr":"1","xp":200,"pb":2,"abilities":{"str":{"score":13,"mod":1,"save":1},"dex":{"score":15,"mod":2,"save":2},"con":{"score":10,"mod":0,"save":0},"int":{"score":7,"mod":-2,"save":-2},"wis":{"score":10,"mod":0,"save":0},"cha":{"score":6,"mod":-2,"save":-2}},"skills":{},"immunities":["Poison","Charmed","Exhaustion","Poisoned"],"senses":"Darkvision 60 ft., Passive Perception 10","languages":"Common","traits":[],"actions":[{"name":"Multiattack","text":"The ghoul makes two Bite attacks."},{"name":"Bite","text":"Melee Attack Roll +4, reach 5 ft. Hit: 5 (1d6 + 2) Piercing damage plus 3 (1d6) Necrotic damage."},{"name":"Claw","text":"Melee Attack Roll +4, reach 5 ft. Hit: 4 (1d4 + 2) Slashing damage. If the target isn''t Undead or elf, it is subjected to: Constitution Saving Throw DC 10. Failure: The target has the Paralyzed condition until the end of its next turn."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-harpy', 'Appendix B: Creatures', 'Harpy', '["Creature Descriptions"]', 100005, 'creature', 'Harpy — Medium Monstrosity, Chaotic Evil.
AC 11, HP 38 (7d8 + 7), Speed walk 20 ft., fly 40 ft..
Abilities: STR 12 (+1), DEX 13 (+1), CON 12 (+1), INT 7 (-2), WIS 10 (+0), CHA 13 (+1).
Senses: Passive Perception 10.
Languages: Common.
Challenge: 1 (XP 200, PB +2).
Claw: Melee Attack Roll +3, reach 5 ft. Hit: 6 (2d4 + 1) Slashing damage.
Luring Song: The harpy sings a magical melody, which lasts until the harpy''s Concentration ends on it. Wisdom Saving Throw: DC 11, each Humanoid and Giant in a 300-foot Emanation originating from the harpy when the song starts. Failure: The target has the Charmed condition until the song ends and repeats the save at the end of each of its turns. While Charmed, the target is Incapacitated and ignores the Luring Song of other harpies. If the target is more than 5 feet from the harpy, the target moves on its turn toward the harpy by the most direct route, trying to get within 5 feet of the harpy. It doesn''t avoid Opportunity Attacks; however, before moving into damaging terrain (such as lava or a pit) and whenever it takes damage from a source other than the harpy, the target repeats the save. Success: The target is immune to this harpy''s Luring Song for 24 hours.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-harpy', '{"name":"Harpy","source":"MM''25 p164","size":"Medium","type":"Monstrosity","alignment":"Chaotic Evil","ac":11,"init":1,"hp_avg":38,"hp_formula":"7d8 + 7","speed":{"walk":20,"fly":40},"cr":"1","xp":200,"pb":2,"abilities":{"str":{"score":12,"mod":1,"save":1},"dex":{"score":13,"mod":1,"save":1},"con":{"score":12,"mod":1,"save":1},"int":{"score":7,"mod":-2,"save":-2},"wis":{"score":10,"mod":0,"save":0},"cha":{"score":13,"mod":1,"save":1}},"skills":{},"senses":"Passive Perception 10","languages":"Common","traits":[],"actions":[{"name":"Claw","text":"Melee Attack Roll +3, reach 5 ft. Hit: 6 (2d4 + 1) Slashing damage."},{"name":"Luring Song","text":"The harpy sings a magical melody, which lasts until the harpy''s Concentration ends on it. Wisdom Saving Throw: DC 11, each Humanoid and Giant in a 300-foot Emanation originating from the harpy when the song starts. Failure: The target has the Charmed condition until the song ends and repeats the save at the end of each of its turns. While Charmed, the target is Incapacitated and ignores the Luring Song of other harpies. If the target is more than 5 feet from the harpy, the target moves on its turn toward the harpy by the most direct route, trying to get within 5 feet of the harpy. It doesn''t avoid Opportunity Attacks; however, before moving into damaging terrain (such as lava or a pit) and whenever it takes damage from a source other than the harpy, the target repeats the save. Success: The target is immune to this harpy''s Luring Song for 24 hours."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-kobold-tinkerer', 'Appendix B: Creatures', 'Kobold Tinkerer', '["Creature Descriptions"]', 100006, 'creature', 'Kobold Tinkerer — Small Humanoid, Any Alignment.
AC 12, HP 10 (3d6), Speed walk 30 ft., fly 10 ft..
Abilities: STR 7 (-2), DEX 14 (+2), CON 10 (+0), INT 15 (+2), WIS 7 (-2), CHA 9 (-1).
Skills: Arcana +4, Perception +0.
Senses: Darkvision 60 ft., Passive Perception 10.
Languages: Common, Draconic.
Challenge: 1/4 (XP 50, PB +2).
Inquiring Mind (1/Day): The kobold can cast detect magic, requiring no components and using Intelligence as the spellcasting ability.
Pack Tactics: The kobold has Advantage on an attack roll against a creature if at least one of its allies is within 5 feet of the creature and the ally isn''t Incapacitated.
Sunlight Sensitivity: While in sunlight, the kobold has Disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.
Dagger: Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage.
Alchemical Flame (Recharge 6): The kobold unleashes fire in a 15-foot cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 10 (3d6) fire damage on a failed saving throw, or half as much damage on a successful one.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-kobold-tinkerer', '{"name":"Kobold Tinkerer","source":"DoSI p43","size":"Small","type":"Humanoid","alignment":"Any Alignment","ac":12,"init":2,"hp_avg":10,"hp_formula":"3d6","speed":{"walk":30,"fly":10},"cr":"1/4","xp":50,"pb":2,"abilities":{"str":{"score":7,"mod":-2,"save":-2},"dex":{"score":14,"mod":2,"save":2},"con":{"score":10,"mod":0,"save":0},"int":{"score":15,"mod":2,"save":2},"wis":{"score":7,"mod":-2,"save":-2},"cha":{"score":9,"mod":-1,"save":-1}},"skills":{"Arcana":4,"Perception":0},"gear":["Dagger"],"senses":"Darkvision 60 ft., Passive Perception 10","languages":"Common, Draconic","traits":[{"name":"Inquiring Mind (1/Day)","text":"The kobold can cast detect magic, requiring no components and using Intelligence as the spellcasting ability."},{"name":"Pack Tactics","text":"The kobold has Advantage on an attack roll against a creature if at least one of its allies is within 5 feet of the creature and the ally isn''t Incapacitated."},{"name":"Sunlight Sensitivity","text":"While in sunlight, the kobold has Disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}],"actions":[{"name":"Dagger","text":"Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage."},{"name":"Alchemical Flame (Recharge 6)","text":"The kobold unleashes fire in a 15-foot cone. Each creature in that area must make a DC 12 Dexterity saving throw, taking 10 (3d6) fire damage on a failed saving throw, or half as much damage on a successful one."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-kobold-warrior', 'Appendix B: Creatures', 'Kobold Warrior', '["Creature Descriptions"]', 100007, 'creature', 'Kobold Warrior — Small Dragon, Neutral.
AC 14, HP 7 (3d6 - 3), Speed walk 30 ft..
Abilities: STR 7 (-2), DEX 15 (+2), CON 9 (-1), INT 8 (-1), WIS 7 (-2), CHA 8 (-1).
Senses: Darkvision 60 ft., Passive Perception 8.
Languages: Common, Draconic.
Challenge: 1/8 (XP 25, PB +2).
Pack Tactics: The kobold has Advantage on an attack roll against a creature if at least one of the kobold''s allies is within 5 feet of the creature and the ally doesn''t have the Incapacitated condition.
Sunlight Sensitivity: While in sunlight, the kobold has Disadvantage on ability checks and attack rolls.
Dagger: Melee or Ranged Attack Roll: +4, reach 5 ft. or range 20/60 ft. Hit: 4 (1d4 + 2) Piercing damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-kobold-warrior', '{"name":"Kobold Warrior","source":"MM''25 p185","size":"Small","type":"Dragon","alignment":"Neutral","ac":14,"init":2,"hp_avg":7,"hp_formula":"3d6 - 3","speed":{"walk":30},"cr":"1/8","xp":25,"pb":2,"abilities":{"str":{"score":7,"mod":-2,"save":-2},"dex":{"score":15,"mod":2,"save":2},"con":{"score":9,"mod":-1,"save":-1},"int":{"score":8,"mod":-1,"save":-1},"wis":{"score":7,"mod":-2,"save":-2},"cha":{"score":8,"mod":-1,"save":-1}},"skills":{},"gear":["three Daggers"],"senses":"Darkvision 60 ft., Passive Perception 8","languages":"Common, Draconic","traits":[{"name":"Pack Tactics","text":"The kobold has Advantage on an attack roll against a creature if at least one of the kobold''s allies is within 5 feet of the creature and the ally doesn''t have the Incapacitated condition."},{"name":"Sunlight Sensitivity","text":"While in sunlight, the kobold has Disadvantage on ability checks and attack rolls."}],"actions":[{"name":"Dagger","text":"Melee or Ranged Attack Roll: +4, reach 5 ft. or range 20/60 ft. Hit: 4 (1d4 + 2) Piercing damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-myconid-adult', 'Appendix B: Creatures', 'Myconid Adult', '["Creature Descriptions"]', 100008, 'creature', 'Myconid Adult — Medium Plant, Lawful Neutral.
AC 12, HP 16 (3d8 + 3), Speed walk 20 ft..
Abilities: STR 10 (+0), DEX 10 (+0), CON 12 (+1), INT 10 (+0), WIS 13 (+1), CHA 7 (-2).
Senses: Darkvision 120 ft., Passive Perception 11.
Languages: Telepathy 240 ft..
Challenge: 1/2 (XP 100, PB +2).
Sun Sickness: While in sunlight, the myconid has Disadvantage on D20 Tests. The myconid dies if it spends more than 1 hour in sunlight.
Slam: Melee Attack Roll +2, reach 5 ft. Hit: 4 (1d8) Bludgeoning damage plus 3 (1d6) Poison damage.
Pacifying Spores (1/Day): Constitution Saving Throw: DC 11, one creature the myconid can see within 10 feet. Failure: The target has the Stunned condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically.
Rapport Spores: The myconid expels spores in a 30-foot Emanation originating from itself. Creatures in that area with an Intelligence score of 2 or higher that aren''t Constructs, Elementals, or Undead gain telepathy with a range of 30 feet for 1 hour.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-myconid-adult', '{"name":"Myconid Adult","source":"MM''25 p223","size":"Medium","type":"Plant","alignment":"Lawful Neutral","ac":12,"init":0,"hp_avg":16,"hp_formula":"3d8 + 3","speed":{"walk":20},"cr":"1/2","xp":100,"pb":2,"abilities":{"str":{"score":10,"mod":0,"save":0},"dex":{"score":10,"mod":0,"save":0},"con":{"score":12,"mod":1,"save":1},"int":{"score":10,"mod":0,"save":0},"wis":{"score":13,"mod":1,"save":1},"cha":{"score":7,"mod":-2,"save":-2}},"skills":{},"senses":"Darkvision 120 ft., Passive Perception 11","languages":"Telepathy 240 ft.","traits":[{"name":"Sun Sickness","text":"While in sunlight, the myconid has Disadvantage on D20 Tests. The myconid dies if it spends more than 1 hour in sunlight."}],"actions":[{"name":"Slam","text":"Melee Attack Roll +2, reach 5 ft. Hit: 4 (1d8) Bludgeoning damage plus 3 (1d6) Poison damage."},{"name":"Pacifying Spores (1/Day)","text":"Constitution Saving Throw: DC 11, one creature the myconid can see within 10 feet. Failure: The target has the Stunned condition and repeats the save at the end of each of its turns, ending the effect on itself on a success. After 1 minute, it succeeds automatically."},{"name":"Rapport Spores","text":"The myconid expels spores in a 30-foot Emanation originating from itself. Creatures in that area with an Intelligence score of 2 or higher that aren''t Constructs, Elementals, or Undead gain telepathy with a range of 30 feet for 1 hour."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-myconid-sprout', 'Appendix B: Creatures', 'Myconid Sprout', '["Creature Descriptions"]', 100009, 'creature', 'Myconid Sprout — Small Plant, Lawful Neutral.
AC 10, HP 3 (1d6), Speed walk 10 ft..
Abilities: STR 8 (-1), DEX 10 (+0), CON 10 (+0), INT 8 (-1), WIS 11 (+0), CHA 5 (-3).
Senses: Darkvision 120 ft., Passive Perception 10.
Languages: Telepathy 240 ft..
Challenge: 0 (XP 10, PB +2).
Sun Sickness: While in sunlight, the myconid has Disadvantage on D20 Tests. The myconid dies if it spends more than 1 hour in sunlight.
Slam: Melee Attack Roll +1, reach 5 ft. Hit: 1 (1d4 - 1) Bludgeoning damage plus 2 (1d4) Poison damage.
Rapport Spores: The myconid expels spores in a 30-foot Emanation originating from itself. Creatures in that area with an Intelligence score of 2 or higher that aren''t Constructs, Elementals, or Undead gain telepathy with a range of 30 feet for 1 hour.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-myconid-sprout', '{"name":"Myconid Sprout","source":"MM''25 p222","size":"Small","type":"Plant","alignment":"Lawful Neutral","ac":10,"init":0,"hp_avg":3,"hp_formula":"1d6","speed":{"walk":10},"cr":"0","xp":10,"pb":2,"abilities":{"str":{"score":8,"mod":-1,"save":-1},"dex":{"score":10,"mod":0,"save":0},"con":{"score":10,"mod":0,"save":0},"int":{"score":8,"mod":-1,"save":-1},"wis":{"score":11,"mod":0,"save":0},"cha":{"score":5,"mod":-3,"save":-3}},"skills":{},"senses":"Darkvision 120 ft., Passive Perception 10","languages":"Telepathy 240 ft.","traits":[{"name":"Sun Sickness","text":"While in sunlight, the myconid has Disadvantage on D20 Tests. The myconid dies if it spends more than 1 hour in sunlight."}],"actions":[{"name":"Slam","text":"Melee Attack Roll +1, reach 5 ft. Hit: 1 (1d4 - 1) Bludgeoning damage plus 2 (1d4) Poison damage."},{"name":"Rapport Spores","text":"The myconid expels spores in a 30-foot Emanation originating from itself. Creatures in that area with an Intelligence score of 2 or higher that aren''t Constructs, Elementals, or Undead gain telepathy with a range of 30 feet for 1 hour."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-owlbear', 'Appendix B: Creatures', 'Owlbear', '["Creature Descriptions"]', 100010, 'creature', 'Owlbear — Large Monstrosity, Unaligned.
AC 13, HP 59 (7d10 + 21), Speed walk 40 ft., climb 40 ft..
Abilities: STR 20 (+5), DEX 12 (+1), CON 17 (+3), INT 3 (-4), WIS 12 (+1), CHA 7 (-2).
Skills: Perception +5.
Senses: Darkvision 60 ft., Passive Perception 15.
Languages: —.
Challenge: 3 (XP 700, PB +2).
Multiattack: The owlbear makes two Rend attacks.
Rend: Melee Attack Roll +7, reach 5 ft. Hit: 14 (2d8 + 5) Slashing damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-owlbear', '{"name":"Owlbear","source":"MM''25 p234","size":"Large","type":"Monstrosity","alignment":"Unaligned","ac":13,"init":1,"hp_avg":59,"hp_formula":"7d10 + 21","speed":{"walk":40,"climb":40},"cr":"3","xp":700,"pb":2,"abilities":{"str":{"score":20,"mod":5,"save":5},"dex":{"score":12,"mod":1,"save":1},"con":{"score":17,"mod":3,"save":3},"int":{"score":3,"mod":-4,"save":-4},"wis":{"score":12,"mod":1,"save":1},"cha":{"score":7,"mod":-2,"save":-2}},"skills":{"Perception":5},"senses":"Darkvision 60 ft., Passive Perception 15","languages":"—","traits":[],"actions":[{"name":"Multiattack","text":"The owlbear makes two Rend attacks."},{"name":"Rend","text":"Melee Attack Roll +7, reach 5 ft. Hit: 14 (2d8 + 5) Slashing damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-sinensa', 'Appendix B: Creatures', 'Sinensa', '["Creature Descriptions"]', 100011, 'creature', 'Sinensa — Large Plant, Lawful Neutral.
AC 13, HP 60 (8d10 + 16), Speed walk 30 ft..
Abilities: STR 12 (+1), DEX 10 (+0), CON 14 (+2), INT 13 (+1), WIS 15 (+2), CHA 10 (+0).
Senses: Darkvision 120 ft., Passive Perception 12.
Languages: —.
Challenge: 2 (XP 450, PB +2).
Distress Spores: When Sinensa takes damage, all other myconids within 240 feet of it can sense its pain.
Sun Sickness: While in sunlight, Sinensa has Disadvantage on ability checks, attack rolls, and saving throws. Sinensa dies if it spends more than 1 hour in direct sunlight.
Multiattack: Sinensa makes one Fist attack and uses its Hallucination Spores.
Fist: Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 8 (3d4 + 1) bludgeoning damage plus 7 (2d4) poison damage.
Hallucination Spores: Sinensa ejects spores at one creature it can see within 5 feet of it. The target must succeed on a DC 12 Constitution saving throw or be poisoned for 1 minute. The poisoned target is incapacitated while it hallucinates. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.
Rapport Spores: A 30-foot radius of spores extends from Sinensa. These spores can go around corners. Affected creatures with an Intelligence score of 2 or higher that aren''t undead, constructs, or elementals can communicate telepathically with one another while within 30 feet of each other. The effect lasts for 1 hour.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-sinensa', '{"name":"Sinensa","source":"DoSI p45","size":"Large","type":"Plant","alignment":"Lawful Neutral","ac":13,"ac_note":"natural armor","init":0,"hp_avg":60,"hp_formula":"8d10 + 16","speed":{"walk":30},"cr":"2","xp":450,"pb":2,"abilities":{"str":{"score":12,"mod":1,"save":1},"dex":{"score":10,"mod":0,"save":0},"con":{"score":14,"mod":2,"save":2},"int":{"score":13,"mod":1,"save":1},"wis":{"score":15,"mod":2,"save":2},"cha":{"score":10,"mod":0,"save":0}},"skills":{},"senses":"Darkvision 120 ft., Passive Perception 12","languages":"—","traits":[{"name":"Distress Spores","text":"When Sinensa takes damage, all other myconids within 240 feet of it can sense its pain."},{"name":"Sun Sickness","text":"While in sunlight, Sinensa has Disadvantage on ability checks, attack rolls, and saving throws. Sinensa dies if it spends more than 1 hour in direct sunlight."}],"actions":[{"name":"Multiattack","text":"Sinensa makes one Fist attack and uses its Hallucination Spores."},{"name":"Fist","text":"Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 8 (3d4 + 1) bludgeoning damage plus 7 (2d4) poison damage."},{"name":"Hallucination Spores","text":"Sinensa ejects spores at one creature it can see within 5 feet of it. The target must succeed on a DC 12 Constitution saving throw or be poisoned for 1 minute. The poisoned target is incapacitated while it hallucinates. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success."},{"name":"Rapport Spores","text":"A 30-foot radius of spores extends from Sinensa. These spores can go around corners. Affected creatures with an Intelligence score of 2 or higher that aren''t undead, constructs, or elementals can communicate telepathically with one another while within 30 feet of each other. The effect lasts for 1 hour."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-runara', 'Appendix B: Creatures', 'Runara', '["Creature Descriptions"]', 100012, 'creature', 'Runara — Huge Dragon, Lawful Good.
AC 19, HP 212 (17d12 + 102), Speed walk 40 ft., fly 80 ft., swim 40 ft..
Abilities: STR 25 (+7), DEX 10 (+0), CON 23 (+6), INT 16 (+3), WIS 15 (+2), CHA 19 (+4).
Skills: Insight +7, Perception +12, Stealth +5.
Immunities: Lightning.
Senses: Blindsight 60 ft., Darkvision 120 ft., Passive Perception 22.
Languages: Common, Draconic.
Challenge: 13 (XP 10000, PB +5).
Amphibious: Runara can breathe air and water.
Legendary Resistance (3/Day): If Runara fails a saving throw, it can choose to succeed instead.
Multiattack: Runara can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.
Bite: Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 18 (2d10 + 7) piercing damage.
Claw: Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 14 (2d6 + 7) slashing damage.
Frightful Presence: Each creature of Runara''s choice that is within 120 feet of Runara and aware of it must succeed on a DC 17 Wisdom saving throw or become Frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a creature''s saving throw is successful or the effect ends for it, the creature is immune to Runara''s Frightful Presence for the next 24 hours.
Breath Weapons (Recharge 5-6): Runara uses one of the following breath weapons: Lightning Breath — exhales lightning in a 90-foot line that is 5 feet wide; each creature in that line must make a DC 19 Dexterity saving throw, taking 66 (12d10) lightning damage on a failed save, or half as much damage on a successful one. Repulsion Breath — exhales repulsion energy in a 30-foot cone; each creature in that area must succeed on a DC 19 Strength saving throw or be pushed 60 feet away from Runara.
Change Shape: Runara magically transforms into a Humanoid or Beast that is Medium or Small, while retaining her game statistics (other than her size). This transformation ends if Runara is reduced to 0 hit points or uses a bonus action to end it.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-runara', '{"name":"Runara","source":"DoSI p40","size":"Huge","type":"Dragon","alignment":"Lawful Good","ac":19,"ac_note":"natural armor","init":0,"hp_avg":212,"hp_formula":"17d12 + 102","speed":{"walk":40,"fly":80,"swim":40},"cr":"13","xp":10000,"pb":5,"abilities":{"str":{"score":25,"mod":7,"save":7},"dex":{"score":10,"mod":0,"save":5},"con":{"score":23,"mod":6,"save":11},"int":{"score":16,"mod":3,"save":3},"wis":{"score":15,"mod":2,"save":7},"cha":{"score":19,"mod":4,"save":9}},"skills":{"Insight":7,"Perception":12,"Stealth":5},"immunities":["Lightning"],"senses":"Blindsight 60 ft., Darkvision 120 ft., Passive Perception 22","languages":"Common, Draconic","traits":[{"name":"Amphibious","text":"Runara can breathe air and water."},{"name":"Legendary Resistance (3/Day)","text":"If Runara fails a saving throw, it can choose to succeed instead."}],"actions":[{"name":"Multiattack","text":"Runara can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."},{"name":"Bite","text":"Melee Weapon Attack: +12 to hit, reach 10 ft., one target. Hit: 18 (2d10 + 7) piercing damage."},{"name":"Claw","text":"Melee Weapon Attack: +12 to hit, reach 5 ft., one target. Hit: 14 (2d6 + 7) slashing damage."},{"name":"Frightful Presence","text":"Each creature of Runara''s choice that is within 120 feet of Runara and aware of it must succeed on a DC 17 Wisdom saving throw or become Frightened for 1 minute. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a creature''s saving throw is successful or the effect ends for it, the creature is immune to Runara''s Frightful Presence for the next 24 hours."},{"name":"Breath Weapons (Recharge 5-6)","text":"Runara uses one of the following breath weapons: Lightning Breath — exhales lightning in a 90-foot line that is 5 feet wide; each creature in that line must make a DC 19 Dexterity saving throw, taking 66 (12d10) lightning damage on a failed save, or half as much damage on a successful one. Repulsion Breath — exhales repulsion energy in a 30-foot cone; each creature in that area must succeed on a DC 19 Strength saving throw or be pushed 60 feet away from Runara."},{"name":"Change Shape","text":"Runara magically transforms into a Humanoid or Beast that is Medium or Small, while retaining her game statistics (other than her size). This transformation ends if Runara is reduced to 0 hit points or uses a bonus action to end it."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-spore-servant-octopus', 'Appendix B: Creatures', 'Spore Servant Octopus', '["Creature Descriptions"]', 100013, 'creature', 'Spore Servant Octopus — Large Plant, Unaligned.
AC 11, HP 52 (8d10 + 8), Speed walk 5 ft., swim 50 ft..
Abilities: STR 17 (+3), DEX 13 (+1), CON 13 (+1), INT 2 (-4), WIS 13 (+1), CHA 1 (-5).
Immunities: Blinded, Charmed, Frightened, Paralyzed.
Senses: Blindsight 30 ft. (blind beyond this radius), Passive Perception 8.
Languages: —.
Challenge: 1 (XP 200, PB +2).
Hold Breath: While out of water, the octopus can hold its breath for 1 hour.
Water Breathing: The octopus can breathe only underwater.
Tentacles: Melee Weapon Attack: +5 to hit, reach 15 ft., one target. Hit: 7 (1d8 + 3) bludgeoning damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-spore-servant-octopus', '{"name":"Spore Servant Octopus","source":"DoSI p46","size":"Large","type":"Plant","alignment":"Unaligned","ac":11,"init":1,"hp_avg":52,"hp_formula":"8d10 + 8","speed":{"walk":5,"swim":50},"cr":"1","xp":200,"pb":2,"abilities":{"str":{"score":17,"mod":3,"save":3},"dex":{"score":13,"mod":1,"save":1},"con":{"score":13,"mod":1,"save":1},"int":{"score":2,"mod":-4,"save":-4},"wis":{"score":13,"mod":1,"save":1},"cha":{"score":1,"mod":-5,"save":-5}},"skills":{},"immunities":["Blinded","Charmed","Frightened","Paralyzed"],"senses":"Blindsight 30 ft. (blind beyond this radius), Passive Perception 8","languages":"—","traits":[{"name":"Hold Breath","text":"While out of water, the octopus can hold its breath for 1 hour."},{"name":"Water Breathing","text":"The octopus can breathe only underwater."}],"actions":[{"name":"Tentacles","text":"Melee Weapon Attack: +5 to hit, reach 15 ft., one target. Hit: 7 (1d8 + 3) bludgeoning damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-stirge', 'Appendix B: Creatures', 'Stirge', '["Creature Descriptions"]', 100014, 'creature', 'Stirge — Tiny Monstrosity, Unaligned.
AC 13, HP 5 (2d4), Speed walk 10 ft., fly 40 ft..
Abilities: STR 4 (-3), DEX 16 (+3), CON 11 (+0), INT 2 (-4), WIS 8 (-1), CHA 6 (-2).
Senses: Darkvision 60 ft., Passive Perception 9.
Languages: —.
Challenge: 1/8 (XP 25, PB +2).
Proboscis: Melee Attack Roll +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage, and the stirge attaches to the target. While attached, the stirge can''t make Proboscis attacks, and the target takes 5 (2d4) Necrotic damage at the start of each of the stirge''s turns. The stirge can detach itself by spending 5 feet of its movement. The target or a creature within 5 feet of it can detach the stirge as an action.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-stirge', '{"name":"Stirge","source":"MM''25 p299","size":"Tiny","type":"Monstrosity","alignment":"Unaligned","ac":13,"init":3,"hp_avg":5,"hp_formula":"2d4","speed":{"walk":10,"fly":40},"cr":"1/8","xp":25,"pb":2,"abilities":{"str":{"score":4,"mod":-3,"save":-3},"dex":{"score":16,"mod":3,"save":3},"con":{"score":11,"mod":0,"save":0},"int":{"score":2,"mod":-4,"save":-4},"wis":{"score":8,"mod":-1,"save":-1},"cha":{"score":6,"mod":-2,"save":-2}},"skills":{},"senses":"Darkvision 60 ft., Passive Perception 9","languages":"—","traits":[],"actions":[{"name":"Proboscis","text":"Melee Attack Roll +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage, and the stirge attaches to the target. While attached, the stirge can''t make Proboscis attacks, and the target takes 5 (2d4) Necrotic damage at the start of each of the stirge''s turns. The stirge can detach itself by spending 5 feet of its movement. The target or a creature within 5 feet of it can detach the stirge as an action."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-tarak', 'Appendix B: Creatures', 'Tarak', '["Creature Descriptions"]', 100015, 'creature', 'Tarak — Medium Humanoid (Human), Lawful Neutral.
AC 13, HP 27 (6d8), Speed walk 30 ft..
Abilities: STR 10 (+0), DEX 16 (+3), CON 10 (+0), INT 12 (+1), WIS 14 (+2), CHA 16 (+3).
Skills: Deception +5, Insight +4, Medicine +4, Nature +3.
Senses: Passive Perception 12.
Languages: Common, Draconic, Thieves'' cant.
Challenge: 1 (XP 200, PB +2).
Multiattack: Tarak makes three Dagger attacks.
Dagger: Melee or Ranged Attack Roll: +5, reach 5 ft. or range 20/60 ft. Hit: 5 (1d4 + 3) piercing damage.
Cunning Action (Bonus Action): Tarak takes the Dash, Disengage, or Hide action.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-tarak', '{"name":"Tarak","source":"DoSI p47","size":"Medium","type":"Humanoid (Human)","alignment":"Lawful Neutral","ac":13,"init":3,"hp_avg":27,"hp_formula":"6d8","speed":{"walk":30},"cr":"1","xp":200,"pb":2,"abilities":{"str":{"score":10,"mod":0,"save":0},"dex":{"score":16,"mod":3,"save":3},"con":{"score":10,"mod":0,"save":0},"int":{"score":12,"mod":1,"save":1},"wis":{"score":14,"mod":2,"save":2},"cha":{"score":16,"mod":3,"save":3}},"skills":{"Deception":5,"Insight":4,"Medicine":4,"Nature":3},"gear":["Dagger"],"senses":"Passive Perception 12","languages":"Common, Draconic, Thieves'' cant","traits":[],"actions":[{"name":"Multiattack","text":"Tarak makes three Dagger attacks."},{"name":"Dagger","text":"Melee or Ranged Attack Roll: +5, reach 5 ft. or range 20/60 ft. Hit: 5 (1d4 + 3) piercing damage."}],"bonus_actions":[{"name":"Cunning Action","text":"Tarak takes the Dash, Disengage, or Hide action."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-varnoth', 'Appendix B: Creatures', 'Varnoth', '["Creature Descriptions"]', 100016, 'creature', 'Varnoth — Medium Humanoid (Human), Neutral Good.
AC 11, HP 39 (6d8 + 12), Speed walk 30 ft..
Abilities: STR 16 (+3), DEX 13 (+1), CON 14 (+2), INT 10 (+0), WIS 11 (+0), CHA 10 (+0).
Skills: Athletics +5, History +2, Perception +2, Religion +2.
Senses: Passive Perception 12.
Languages: Common.
Challenge: 2 (XP 450, PB +2).
Multiattack: Varnoth makes three Shortsword attacks.
Shortsword: Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-varnoth', '{"name":"Varnoth","source":"DoSI p47","size":"Medium","type":"Humanoid (Human)","alignment":"Neutral Good","ac":11,"init":1,"hp_avg":39,"hp_formula":"6d8 + 12","speed":{"walk":30},"cr":"2","xp":450,"pb":2,"abilities":{"str":{"score":16,"mod":3,"save":3},"dex":{"score":13,"mod":1,"save":1},"con":{"score":14,"mod":2,"save":2},"int":{"score":10,"mod":0,"save":0},"wis":{"score":11,"mod":0,"save":0},"cha":{"score":10,"mod":0,"save":0}},"skills":{"Athletics":5,"History":2,"Perception":2,"Religion":2},"gear":["Shortsword"],"senses":"Passive Perception 12","languages":"Common","traits":[],"actions":[{"name":"Multiattack","text":"Varnoth makes three Shortsword attacks."},{"name":"Shortsword","text":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-violet-fungus', 'Appendix B: Creatures', 'Violet Fungus', '["Creature Descriptions"]', 100017, 'creature', 'Violet Fungus — Medium Plant, Unaligned.
AC 5, HP 18 (4d8), Speed walk 5 ft..
Abilities: STR 3 (-4), DEX 1 (-5), CON 10 (+0), INT 1 (-5), WIS 1 (-4), CHA 1 (-5).
Immunities: Blinded, Charmed, Deafened, Frightened.
Senses: Blindsight 30 ft., Passive Perception 6.
Languages: —.
Challenge: 1/4 (XP 50, PB +2).
Multiattack: The fungus makes two Rotting Touch attacks.
Rotting Touch: Melee Attack Roll +2, reach 10 ft. Hit: 4 (1d8) Necrotic damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-violet-fungus', '{"name":"Violet Fungus","source":"MM''25 p126","size":"Medium","type":"Plant","alignment":"Unaligned","ac":5,"init":-5,"hp_avg":18,"hp_formula":"4d8","speed":{"walk":5},"cr":"1/4","xp":50,"pb":2,"abilities":{"str":{"score":3,"mod":-4,"save":-4},"dex":{"score":1,"mod":-5,"save":-5},"con":{"score":10,"mod":0,"save":0},"int":{"score":1,"mod":-5,"save":-5},"wis":{"score":1,"mod":-4,"save":-4},"cha":{"score":1,"mod":-5,"save":-5}},"skills":{},"immunities":["Blinded","Charmed","Deafened","Frightened"],"senses":"Blindsight 30 ft., Passive Perception 6","languages":"—","traits":[],"actions":[{"name":"Multiattack","text":"The fungus makes two Rotting Touch attacks."},{"name":"Rotting Touch","text":"Melee Attack Roll +2, reach 10 ft. Hit: 4 (1d8) Necrotic damage."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-winged-kobold', 'Appendix B: Creatures', 'Winged Kobold', '["Creature Descriptions"]', 100018, 'creature', 'Winged Kobold — Small Dragon, Neutral.
AC 15, HP 10 (4d6 - 4), Speed walk 30 ft., fly 30 ft..
Abilities: STR 7 (-2), DEX 16 (+3), CON 9 (-1), INT 8 (-1), WIS 7 (-2), CHA 8 (-1).
Senses: Darkvision 60 ft., Passive Perception 8.
Languages: Common, Draconic.
Challenge: 1/4 (XP 50, PB +2).
Pack Tactics: The kobold has Advantage on an attack roll against a creature if at least one of the kobold''s allies is within 5 feet of the creature and the ally doesn''t have the Incapacitated condition.
Sunlight Sensitivity: While in sunlight, the kobold has Disadvantage on ability checks and attack rolls.
Dragon-Tooth Blade: Melee Attack Roll +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage.
Chromatic Spittle: Ranged Attack Roll +5, range 30 ft. Hit: 6 (1d6 + 3) damage of a type chosen by the kobold: Acid, Cold, Fire, Lightning, or Poison.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-winged-kobold', '{"name":"Winged Kobold","source":"MM''25 p185","size":"Small","type":"Dragon","alignment":"Neutral","ac":15,"init":3,"hp_avg":10,"hp_formula":"4d6 - 4","speed":{"walk":30,"fly":30},"cr":"1/4","xp":50,"pb":2,"abilities":{"str":{"score":7,"mod":-2,"save":-2},"dex":{"score":16,"mod":3,"save":3},"con":{"score":9,"mod":-1,"save":-1},"int":{"score":8,"mod":-1,"save":-1},"wis":{"score":7,"mod":-2,"save":-2},"cha":{"score":8,"mod":-1,"save":-1}},"skills":{},"senses":"Darkvision 60 ft., Passive Perception 8","languages":"Common, Draconic","traits":[{"name":"Pack Tactics","text":"The kobold has Advantage on an attack roll against a creature if at least one of the kobold''s allies is within 5 feet of the creature and the ally doesn''t have the Incapacitated condition."},{"name":"Sunlight Sensitivity","text":"While in sunlight, the kobold has Disadvantage on ability checks and attack rolls."}],"actions":[{"name":"Dragon-Tooth Blade","text":"Melee Attack Roll +5, reach 5 ft. Hit: 6 (1d6 + 3) Piercing damage."},{"name":"Chromatic Spittle","text":"Ranged Attack Roll +5, range 30 ft. Hit: 6 (1d6 + 3) damage of a type chosen by the kobold: Acid, Cold, Fire, Lightning, or Poison."}]}');
INSERT INTO sections (id, chapter, heading, heading_path, "order", type, dm_only_text, read_aloud_text) VALUES ('creature-zombie', 'Appendix B: Creatures', 'Zombie', '["Creature Descriptions"]', 100019, 'creature', 'Zombie — Medium Undead, Neutral Evil.
AC 8, HP 15 (2d8 + 6), Speed walk 20 ft..
Abilities: STR 13 (+1), DEX 6 (-2), CON 16 (+3), INT 3 (-4), WIS 6 (-2), CHA 5 (-3).
Immunities: Poison, Exhaustion, Poisoned.
Senses: Darkvision 60 ft., Passive Perception 8.
Languages: Understands Common plus one other language but can''t speak.
Challenge: 1/4 (XP 50, PB +2).
Undead Fortitude: If damage reduces the zombie to 0 Hit Points, it makes a Constitution saving throw (DC 5 plus the damage taken) unless the damage is Radiant or from a Critical Hit. On a successful save, the zombie drops to 1 Hit Point instead.
Slam: Melee Attack Roll +3, reach 5 ft. Hit: 5 (1d8 + 1) Bludgeoning damage.', '');
INSERT INTO creature_stats (section_id, stat_block_json) VALUES ('creature-zombie', '{"name":"Zombie","source":"MM''25 p346","size":"Medium","type":"Undead","alignment":"Neutral Evil","ac":8,"init":-2,"hp_avg":15,"hp_formula":"2d8 + 6","speed":{"walk":20},"cr":"1/4","xp":50,"pb":2,"abilities":{"str":{"score":13,"mod":1,"save":1},"dex":{"score":6,"mod":-2,"save":-2},"con":{"score":16,"mod":3,"save":3},"int":{"score":3,"mod":-4,"save":-4},"wis":{"score":6,"mod":-2,"save":-2},"cha":{"score":5,"mod":-3,"save":-3}},"skills":{},"immunities":["Poison","Exhaustion","Poisoned"],"senses":"Darkvision 60 ft., Passive Perception 8","languages":"Understands Common plus one other language but can''t speak","traits":[{"name":"Undead Fortitude","text":"If damage reduces the zombie to 0 Hit Points, it makes a Constitution saving throw (DC 5 plus the damage taken) unless the damage is Radiant or from a Critical Hit. On a successful save, the zombie drops to 1 Hit Point instead."}],"actions":[{"name":"Slam","text":"Melee Attack Roll +3, reach 5 ft. Hit: 5 (1d8 + 1) Bludgeoning damage."}]}');
